"""starters, feedings, observations

Revision ID: 351cda748563
Revises: 3ac91e2efab2
Create Date: 2026-07-28 21:34:21.472294
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "351cda748563"
down_revision: str | None = "3ac91e2efab2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "starter",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("flour_type", sa.String(length=60), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("avatar_object_key", sa.String(length=255), nullable=True),
        sa.Column("ratio_starter", sa.SmallInteger(), nullable=False),
        sa.Column("ratio_flour", sa.SmallInteger(), nullable=False),
        sa.Column("ratio_water", sa.SmallInteger(), nullable=False),
        sa.Column("feed_interval_hours", sa.SmallInteger(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "active",
                "fridge",
                "dormant",
                "retired",
                name="starter_state",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_starter_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_starter")),
    )
    op.create_index(op.f("ix_starter_user_id"), "starter", ["user_id"], unique=False)
    op.create_index(
        "uq_starter_user_name_live",
        "starter",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "feeding",
        sa.Column("starter_id", sa.UUID(), nullable=False),
        sa.Column("fed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("starter_g", sa.Float(), nullable=False),
        sa.Column("flour_g", sa.Float(), nullable=False),
        sa.Column("water_g", sa.Float(), nullable=False),
        sa.Column("flour_blend", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ambient_temp_c", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["starter_id"],
            ["starter.id"],
            name=op.f("fk_feeding_starter_id_starter"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feeding")),
    )
    op.create_index("ix_feeding_starter_fed_at", "feeding", ["starter_id", "fed_at"], unique=False)
    op.create_table(
        "starter_observation",
        sa.Column("starter_id", sa.UUID(), nullable=False),
        sa.Column("feeding_id", sa.UUID(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rise_multiple", sa.Float(), nullable=True),
        sa.Column("peaked", sa.Boolean(), nullable=False),
        sa.Column("float_test_passed", sa.Boolean(), nullable=True),
        sa.Column(
            "aroma",
            sa.Enum(
                "sweet",
                "yeasty",
                "tangy",
                "sour",
                "vinegar",
                "acetone",
                "alcohol",
                "musty",
                name="aroma",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("dough_temp_c", sa.Float(), nullable=True),
        sa.Column("photo_object_key", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feeding_id"],
            ["feeding.id"],
            name=op.f("fk_starter_observation_feeding_id_feeding"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["starter_id"],
            ["starter.id"],
            name=op.f("fk_starter_observation_starter_id_starter"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_starter_observation")),
    )
    op.create_index(
        "ix_starter_observation_starter_observed_at",
        "starter_observation",
        ["starter_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_starter_observation_starter_observed_at", table_name="starter_observation")
    op.drop_table("starter_observation")
    op.drop_index("ix_feeding_starter_fed_at", table_name="feeding")
    op.drop_table("feeding")
    op.drop_index(
        "uq_starter_user_name_live",
        table_name="starter",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_starter_user_id"), table_name="starter")
    op.drop_table("starter")
    # ### end Alembic commands ###
