"""ingredient densities and unit preference

Revision ID: 4f2696a207a3
Revises: 954f0440c488
Create Date: 2026-07-30 00:46:29.099264
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4f2696a207a3"
down_revision: str | None = "954f0440c488"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient_measure",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("grams_per_cup", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("volume_allowed", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_ingredient_measure")),
    )
    op.create_index(
        op.f("ix_ingredient_measure_kind"), "ingredient_measure", ["kind"], unique=False
    )
    op.create_table(
        "user_ingredient_measure",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("grams_per_cup", sa.Float(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["slug"],
            ["ingredient_measure.slug"],
            name=op.f("fk_user_ingredient_measure_slug_ingredient_measure"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_ingredient_measure_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_ingredient_measure")),
        sa.UniqueConstraint("user_id", "slug", name="uq_user_ingredient_measure"),
    )
    op.create_index(
        op.f("ix_user_ingredient_measure_user_id"),
        "user_ingredient_measure",
        ["user_id"],
        unique=False,
    )
    # server_default, not just the model's Python-side default: without it this
    # NOT NULL column cannot be added to a table that already has rows, and
    # autogenerate does not infer one.
    op.add_column(
        "user_profile",
        sa.Column("units", sa.String(length=8), nullable=False, server_default="metric"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "units")
    op.drop_index(op.f("ix_user_ingredient_measure_user_id"), table_name="user_ingredient_measure")
    op.drop_table("user_ingredient_measure")
    op.drop_index(op.f("ix_ingredient_measure_kind"), table_name="ingredient_measure")
    op.drop_table("ingredient_measure")
    # ### end Alembic commands ###
