"""proof sessions and checks

Revision ID: 5b7c2291ae0c
Revises: 351cda748563
Create Date: 2026-07-28 21:50:58.677356
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5b7c2291ae0c"
down_revision: str | None = "351cda748563"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proof_session",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("starter_id", sa.UUID(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "levain",
                "autolyse",
                "bulk",
                "shaped",
                "retard",
                name="proof_stage",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "running", "done", "aborted", name="proof_status", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dough_temp_c", sa.Float(), nullable=False),
        sa.Column("ambient_temp_c", sa.Float(), nullable=True),
        sa.Column("starter_pct", sa.Float(), nullable=False),
        sa.Column("hydration_pct", sa.Float(), nullable=True),
        sa.Column("target_rise_pct", sa.Float(), nullable=False),
        sa.Column("planned_duration_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("predicted_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vigour_used", sa.Float(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["starter_id"],
            ["starter.id"],
            name=op.f("fk_proof_session_starter_id_starter"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_proof_session_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proof_session")),
    )
    op.create_index(op.f("ix_proof_session_user_id"), "proof_session", ["user_id"], unique=False)
    op.create_index(
        "ix_proof_session_user_status", "proof_session", ["user_id", "status"], unique=False
    )
    op.create_table(
        "proof_check",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rise_pct", sa.Float(), nullable=False),
        sa.Column("dough_temp_c", sa.Float(), nullable=True),
        sa.Column(
            "poke_test",
            sa.Enum(
                "springs_back",
                "slow_spring",
                "no_spring",
                name="poke_test",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("photo_object_key", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["proof_session.id"],
            name=op.f("fk_proof_check_session_id_proof_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proof_check")),
    )
    op.create_index(
        "ix_proof_check_session_checked_at",
        "proof_check",
        ["session_id", "checked_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_proof_check_session_checked_at", table_name="proof_check")
    op.drop_table("proof_check")
    op.drop_index("ix_proof_session_user_status", table_name="proof_session")
    op.drop_index(op.f("ix_proof_session_user_id"), table_name="proof_session")
    op.drop_table("proof_session")
    # ### end Alembic commands ###
