"""gamification: xp, achievements, seasons, leaderboard

Revision ID: 657e89e6511d
Revises: 72039cdd2e98
Create Date: 2026-07-29 01:32:54.843080
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "657e89e6511d"
down_revision: str | None = "72039cdd2e98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievement",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "starter",
                "proofing",
                "baking",
                "recipes",
                "community",
                "inventory",
                "dedication",
                name="achievement_category",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "rarity",
            sa.Enum(
                "common",
                "uncommon",
                "rare",
                "epic",
                "legendary",
                name="rarity",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("xp_award", sa.Integer(), nullable=False),
        sa.Column("icon", sa.String(length=8), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requires_photo", sa.Boolean(), nullable=False),
        sa.Column("is_seasonal", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_achievement")),
    )
    op.create_table(
        "season",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_season")),
        sa.UniqueConstraint("name", name=op.f("uq_season_name")),
    )
    op.create_index("ix_season_window", "season", ["starts_at", "ends_at"], unique=False)
    op.create_table(
        "leaderboard_entry",
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("season_xp", sa.Integer(), nullable=False),
        sa.Column("lifetime_xp", sa.Integer(), nullable=False),
        sa.Column("bake_count", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("average_crumb", sa.Float(), nullable=True),
        sa.Column("achievement_count", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
            name=op.f("fk_leaderboard_entry_season_id_season"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_leaderboard_entry_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("season_id", "user_id", name=op.f("pk_leaderboard_entry")),
    )
    op.create_index(
        "ix_leaderboard_season_rank", "leaderboard_entry", ["season_id", "rank"], unique=False
    )
    op.create_table(
        "user_achievement",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("achievement_code", sa.String(length=60), nullable=False),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("earned_value", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["achievement_code"],
            ["achievement.code"],
            name=op.f("fk_user_achievement_achievement_code_achievement"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_achievement_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "achievement_code", name=op.f("pk_user_achievement")),
    )
    op.create_table(
        "xp_event",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rule_code", sa.String(length=60), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
            name=op.f("fk_xp_event_season_id_season"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_xp_event_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xp_event")),
        sa.UniqueConstraint(
            "user_id", "rule_code", "source_type", "source_id", name="uq_xp_event_source"
        ),
    )
    op.create_index("ix_xp_event_season_user", "xp_event", ["season_id", "user_id"], unique=False)
    op.create_index("ix_xp_event_user_created", "xp_event", ["user_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_xp_event_user_created", table_name="xp_event")
    op.drop_index("ix_xp_event_season_user", table_name="xp_event")
    op.drop_table("xp_event")
    op.drop_table("user_achievement")
    op.drop_index("ix_leaderboard_season_rank", table_name="leaderboard_entry")
    op.drop_table("leaderboard_entry")
    op.drop_index("ix_season_window", table_name="season")
    op.drop_table("season")
    op.drop_table("achievement")
    # ### end Alembic commands ###
