"""inventory ledger and bake costing

Revision ID: 72039cdd2e98
Revises: d4ea2ac3d347
Create Date: 2026-07-29 01:19:52.543532
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "72039cdd2e98"
down_revision: str | None = "d4ea2ac3d347"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_item",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "flour",
                "salt",
                "inclusion",
                "other",
                name="item_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("low_threshold_g", sa.Float(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_inventory_item_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_item")),
    )
    op.create_index(op.f("ix_inventory_item_user_id"), "inventory_item", ["user_id"], unique=False)
    op.create_index(
        "uq_inventory_item_user_name_live",
        "inventory_item",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "inventory_transaction",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "purchase",
                "consume",
                "adjust",
                name="transaction_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("delta_g", sa.Float(), nullable=False),
        sa.Column("unit_cost_per_kg", sa.Float(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("bake_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bake_id"],
            ["bake.id"],
            name=op.f("fk_inventory_transaction_bake_id_bake"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory_item.id"],
            name=op.f("fk_inventory_transaction_item_id_inventory_item"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_transaction")),
    )
    op.create_index(
        op.f("ix_inventory_transaction_bake_id"), "inventory_transaction", ["bake_id"], unique=False
    )
    op.create_index(
        "ix_inventory_transaction_item_time",
        "inventory_transaction",
        ["item_id", "occurred_at"],
        unique=False,
    )
    op.add_column("bake", sa.Column("flour_cost", sa.Float(), nullable=True))
    op.add_column("bake", sa.Column("flour_cost_per_loaf", sa.Float(), nullable=True))
    op.add_column(
        "bake", sa.Column("inventory_consumed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bake", "inventory_consumed_at")
    op.drop_column("bake", "flour_cost_per_loaf")
    op.drop_column("bake", "flour_cost")
    op.drop_index("ix_inventory_transaction_item_time", table_name="inventory_transaction")
    op.drop_index(op.f("ix_inventory_transaction_bake_id"), table_name="inventory_transaction")
    op.drop_table("inventory_transaction")
    op.drop_index(
        "uq_inventory_item_user_name_live",
        table_name="inventory_item",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_inventory_item_user_id"), table_name="inventory_item")
    op.drop_table("inventory_item")
    # ### end Alembic commands ###
