"""notifications: scheduling, channels, inbox

Revision ID: 954f0440c488
Revises: 657e89e6511d
Create Date: 2026-07-29 02:09:58.775689
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "954f0440c488"
down_revision: str | None = "657e89e6511d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inapp_notification",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "event",
            sa.Enum(
                "starter.feed_due",
                "starter.streak_at_risk",
                "proof.ready",
                "proof.retard_remove",
                "inventory.low",
                "achievement.earned",
                "digest.weekly",
                name="notification_event",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_inapp_notification_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inapp_notification")),
    )
    op.create_index(
        "ix_inapp_notification_user_time",
        "inapp_notification",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notification_channel",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "inapp",
                "email",
                "webpush",
                "ntfy",
                name="channel_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=60), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_hash", sa.String(length=64), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_notification_channel_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_channel")),
    )
    op.create_index(
        op.f("ix_notification_channel_user_id"), "notification_channel", ["user_id"], unique=False
    )
    op.create_index(
        "uq_notification_channel_target",
        "notification_channel",
        ["user_id", "kind", "target_hash"],
        unique=True,
    )
    op.create_table(
        "notification_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("quiet_hours_start", sa.SmallInteger(), nullable=True),
        sa.Column("quiet_hours_end", sa.SmallInteger(), nullable=True),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("digest_enabled", sa.Boolean(), nullable=False),
        sa.Column("digest_weekday", sa.SmallInteger(), nullable=False),
        sa.Column("digest_hour", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_notification_settings_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_notification_settings")),
    )
    op.create_table(
        "scheduled_notification",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "event",
            sa.Enum(
                "starter.feed_due",
                "starter.streak_at_risk",
                "proof.ready",
                "proof.retard_remove",
                "inventory.low",
                "achievement.earned",
                "digest.weekly",
                name="notification_event",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "claimed",
                "sent",
                "failed",
                "cancelled",
                name="delivery_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("dedupe_key", sa.String(length=120), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_scheduled_notification_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_notification")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_scheduled_notification_dedupe_key")),
    )
    op.create_index(
        "ix_scheduled_notification_due",
        "scheduled_notification",
        ["status", "due_at"],
        unique=False,
    )
    op.create_table(
        "notification_log",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_id", sa.UUID(), nullable=True),
        sa.Column(
            "event",
            sa.Enum(
                "starter.feed_due",
                "starter.streak_at_risk",
                "proof.ready",
                "proof.retard_remove",
                "inventory.low",
                "achievement.earned",
                "digest.weekly",
                name="notification_event",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel_kind",
            sa.Enum(
                "inapp",
                "email",
                "webpush",
                "ntfy",
                name="channel_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheduled_id"],
            ["scheduled_notification.id"],
            name=op.f("fk_notification_log_scheduled_id_scheduled_notification"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_notification_log_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_log")),
    )
    op.create_index(
        "ix_notification_log_user_time", "notification_log", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_log_user_time", table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index("ix_scheduled_notification_due", table_name="scheduled_notification")
    op.drop_table("scheduled_notification")
    op.drop_table("notification_settings")
    op.drop_index("uq_notification_channel_target", table_name="notification_channel")
    op.drop_index(op.f("ix_notification_channel_user_id"), table_name="notification_channel")
    op.drop_table("notification_channel")
    op.drop_index("ix_inapp_notification_user_time", table_name="inapp_notification")
    op.drop_table("inapp_notification")
    # ### end Alembic commands ###
