"""recipes, bakes, photos

Revision ID: d4ea2ac3d347
Revises: 5b7c2291ae0c
Create Date: 2026-07-29 01:06:55.296767
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d4ea2ac3d347"
down_revision: str | None = "5b7c2291ae0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("forked_from_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("default_dough_weight_g", sa.Float(), nullable=False),
        sa.Column("starter_hydration_pct", sa.Float(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("star_count", sa.Integer(), nullable=False),
        sa.Column("fork_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["forked_from_id"],
            ["recipe.id"],
            name=op.f("fk_recipe_forked_from_id_recipe"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("fk_recipe_owner_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe")),
    )
    op.create_index(op.f("ix_recipe_forked_from_id"), "recipe", ["forked_from_id"], unique=False)
    op.create_index(op.f("ix_recipe_owner_id"), "recipe", ["owner_id"], unique=False)
    op.create_index(
        "ix_recipe_public_stars",
        "recipe",
        ["is_public", sa.literal_column("star_count DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_recipe_owner_name_live",
        "recipe",
        ["owner_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "bake",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("recipe_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress", "done", "abandoned", name="bake_status", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_flour_g", sa.Float(), nullable=True),
        sa.Column("hydration_pct", sa.Float(), nullable=True),
        sa.Column("salt_pct", sa.Float(), nullable=True),
        sa.Column("starter_pct", sa.Float(), nullable=True),
        sa.Column("flour_blend", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("loaf_count", sa.SmallInteger(), nullable=False),
        sa.Column("oven_temp_c", sa.Float(), nullable=True),
        sa.Column("bake_time_minutes", sa.SmallInteger(), nullable=True),
        sa.Column("vessel", sa.String(length=60), nullable=True),
        sa.Column("scoring_pattern", sa.String(length=60), nullable=True),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipe.id"], name=op.f("fk_bake_recipe_id_recipe"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_bake_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bake")),
    )
    op.create_index(op.f("ix_bake_user_id"), "bake", ["user_id"], unique=False)
    op.create_index(
        "ix_bake_user_started",
        "bake",
        ["user_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "recipe_ingredient",
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "flour",
                "liquid",
                "salt",
                "starter",
                "inclusion",
                name="ingredient_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
            name=op.f("fk_recipe_ingredient_recipe_id_recipe"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_ingredient")),
    )
    op.create_index(
        "ix_recipe_ingredient_recipe",
        "recipe_ingredient",
        ["recipe_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "recipe_star",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("recipe_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
            name=op.f("fk_recipe_star_recipe_id_recipe"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_recipe_star_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "recipe_id", name=op.f("pk_recipe_star")),
    )
    op.create_table(
        "bake_photo",
        sa.Column("bake_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "crumb",
                "crust",
                "shaped",
                "proof",
                "other",
                name="photo_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("caption", sa.String(length=200), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bake_id"], ["bake.id"], name=op.f("fk_bake_photo_bake_id_bake"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bake_photo")),
        sa.UniqueConstraint("object_key", name=op.f("uq_bake_photo_object_key")),
    )
    op.create_index("ix_bake_photo_bake", "bake_photo", ["bake_id", "sort_order"], unique=False)
    op.create_table(
        "bake_rating",
        sa.Column("bake_id", sa.UUID(), nullable=False),
        sa.Column("crumb", sa.SmallInteger(), nullable=True),
        sa.Column("oven_spring", sa.SmallInteger(), nullable=True),
        sa.Column("crust", sa.SmallInteger(), nullable=True),
        sa.Column("sourness", sa.SmallInteger(), nullable=True),
        sa.Column("overall", sa.SmallInteger(), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bake_id"], ["bake.id"], name=op.f("fk_bake_rating_bake_id_bake"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("bake_id", name=op.f("pk_bake_rating")),
    )
    op.add_column("proof_session", sa.Column("bake_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_proof_session_bake_id"), "proof_session", ["bake_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_proof_session_bake_id_bake"),
        "proof_session",
        "bake",
        ["bake_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_proof_session_bake_id_bake"), "proof_session", type_="foreignkey")
    op.drop_index(op.f("ix_proof_session_bake_id"), table_name="proof_session")
    op.drop_column("proof_session", "bake_id")
    op.drop_table("bake_rating")
    op.drop_index("ix_bake_photo_bake", table_name="bake_photo")
    op.drop_table("bake_photo")
    op.drop_table("recipe_star")
    op.drop_index("ix_recipe_ingredient_recipe", table_name="recipe_ingredient")
    op.drop_table("recipe_ingredient")
    op.drop_index("ix_bake_user_started", table_name="bake")
    op.drop_index(op.f("ix_bake_user_id"), table_name="bake")
    op.drop_table("bake")
    op.drop_index(
        "uq_recipe_owner_name_live",
        table_name="recipe",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_recipe_public_stars",
        table_name="recipe",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_recipe_owner_id"), table_name="recipe")
    op.drop_index(op.f("ix_recipe_forked_from_id"), table_name="recipe")
    op.drop_table("recipe")
    # ### end Alembic commands ###
